### ISSUE TITLE
Rendering issue in MacOS Preview 11

### ISSUE THREAD

**Issue by tzugen** [ateliertriay/bricolage#8]
In the Preview app of MacOS 10.15 there is a rendering issue with the capital A.
I think if the paths would be merged it would go away....

I attach a test pdf below
[Test.pdf](https://github.com/ateliertriay/bricolage/files/12540760/Test.pdf)
![Bildschirmfoto 2023-09-06 um 19 27 32](https://github.com/ateliertriay/bricolage/assets/67737443/14e60dd9-6c95-4560-807a-a4b73cadcc59)

**Comment by kenmcd** [comment]
You must be using the fonts from Google Fonts.
They leave the overlaps in because applications should be able handle overlaps properly.

Your Options:
The rendering problem is in your operating system - so you could update your OS to 11 or 12 and it will work properly.
OR
Use the static TTF fonts from this repository - which do have the overlaps removed.
OR
Use the static OTF fonts from this repository - static OTF fonts do not have overlaps.

**Comment by tzugen** [comment]
Perfect thanks for the quick help ♥️
Beautiful font btw!
